server:
  port: 8080
spring:
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    #调试时候写false 打包写true
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org.springframework.web: INFO
maxmind:
  geoip:
    geolite2-city-mmdb: classpath:GeoLite2/GeoLite2-ASN.mmdb
