server:
  port: 80
spring:
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
