server:
    port: 8080
spring:
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
